const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const sitemap = require('./sitemap.cjs');
const testBase = process.env.BCUT_TEST_TMP || os.tmpdir();
const root = fs.mkdtempSync(path.join(testBase, 'bcut-sitemap-test-'));
const write = (file, text) => { fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true }); fs.writeFileSync(path.join(root, file), text); };
const urls = [sitemap.SITE + '/', sitemap.SITE + '/models/a.html', sitemap.SITE + '/models/b.html'];
const xml = '<?xml version="1.0"?><urlset>' + urls.map(url => '<url><loc>' + url + '</loc><lastmod>2026-10-08</lastmod></url>').join('') + '</urlset>';
let checks = 0;
try {
  write('index.html', '<h1>Catalogue</h1>');
  write('data.json', '{"works":{}}');
  write('model-page.js', '/* shared model runtime */');
  write('assets/a.jpg', 'original image');
  write('models/a.html', '<h1>A 1 work</h1><script src="../model-page.js"></script><img src="../assets/a.jpg">');
  write('models/b.html', '<h1>B 1 work</h1><script src="../model-page.js"></script><a class="chip" href="a.html">A<b>화보 1</b></a>');
  const git = args => execFileSync('git', args, { cwd: root, stdio: 'pipe', env: { ...process.env, GIT_AUTHOR_DATE: '2026-10-09T16:00:00Z', GIT_COMMITTER_DATE: '2026-10-09T16:00:00Z' } });
  git(['init', '-q']); git(['add', '.']); git(['-c', 'user.name=Test', '-c', 'user.email=test@example.invalid', 'commit', '-qm', 'Initial public content']);
  const first = sitemap.generate(root, xml, null, '2026-10-10');
  assert.equal(first.pages, 3); assert.equal(first.state.pages[urls[1]].lastmod, '2026-10-10'); checks++;
  const next = sitemap.generate(root, first.sitemap, first.state, '2026-10-11');
  assert.equal(next.changed, 0); assert.equal(next.sitemap, first.sitemap); checks++;
  write('models/a.html', '<h1>A 2 works</h1>\n<script src="../model-page.js"></script><img src="../assets/a.jpg">');
  write('data.json', '{"works":{"2":{"title":"New work"}}}');
  const added = sitemap.generate(root, next.sitemap, next.state, '2026-10-11');
  assert.equal(added.state.pages[urls[1]].lastmod, '2026-10-11');
  assert.equal(added.state.pages[urls[0]].lastmod, '2026-10-11');
  assert.equal(added.state.pages[urls[2]].lastmod, '2026-10-10'); checks++;
  const stable = sitemap.generate(root, added.sitemap, added.state, '2026-10-12');
  assert.equal(stable.changed, 0); assert.equal(stable.sitemap, added.sitemap); checks++;
  write('models/b.html', fs.readFileSync(path.join(root, 'models/b.html'), 'utf8').replace('화보 1', '화보 2'));
  assert.equal(sitemap.generate(root, stable.sitemap, stable.state, '2026-10-12').changed, 0); checks++;
  write('assets/a.jpg', 'manually replaced image');
  const image = sitemap.generate(root, stable.sitemap, stable.state, '2026-10-12');
  assert.equal(image.changed, 1); assert.equal(image.state.pages[urls[1]].lastmod, '2026-10-12'); checks++;
  write('model-page.js', '/* changed model runtime */');
  const shared = sitemap.generate(root, image.sitemap, image.state, '2026-10-13');
  assert.equal(shared.changed, 2); assert.equal(shared.state.pages[urls[0]].lastmod, '2026-10-11'); checks++;
  const modelText = fs.readFileSync(path.join(root, 'models/a.html'), 'utf8');
  write('models/a.html', modelText.replace(/\n/g, '\r\n'));
  assert.equal(sitemap.generate(root, shared.sitemap, shared.state, '2026-10-14').changed, 0); checks++;
  write('data.json', '{"works":{"9":{"pub":"2026-10-16","title":"Registered upcoming work"}}}');
  const scheduled = sitemap.generate(root, shared.sitemap, shared.state, '2026-10-14');
  assert.equal(sitemap.generate(root, scheduled.sitemap, scheduled.state, '2026-10-15').changed, 0); checks++;
  const released = sitemap.generate(root, scheduled.sitemap, scheduled.state, '2026-10-16');
  assert.equal(released.changed, 1); assert.equal(released.state.pages[urls[0]].lastmod, '2026-10-16'); checks++;
  assert.throws(() => sitemap.readEntries(xml.replace('</urlset>', xml.match(/<url>[\s\S]*?<\/url>/)[0] + '</urlset>')), /Duplicate/); checks++;
  assert.throws(() => sitemap.readEntries(xml.replace('2026-10-08', '2026-02-30')), /Invalid/); checks++;
  assert.throws(() => sitemap.pageFile('https://example.com/a.html'), /Invalid/); checks++;
  assert.throws(() => sitemap.validateState({ ...shared.state, site: 'https://example.com' }, '2026-10-14'), /Invalid/); checks++;
  assert.throws(() => sitemap.validateState(shared.state, '2026-10-10'), /Invalid/); checks++;
  assert.throws(() => sitemap.generate(root, xml.replace('/models/a.html', '/models/missing.html'), null, '2026-10-14'), /ENOENT/); checks++;
  console.log(JSON.stringify({ result: 'PASS', checks, scenarios: ['KST Git dates', 'unchanged daily build', 'isolated new work', 'manual image replacement', 'shared runtime update', 'line endings', 'duplicate/malformed/missing URL', 'invalid previous state'] }));
} finally {
  const resolved = fs.realpathSync(root);
  assert(path.dirname(resolved) === fs.realpathSync(testBase) && path.basename(resolved).startsWith('bcut-sitemap-test-'));
  fs.rmSync(resolved, { recursive: true, force: true });
}
